apiVersion: v1
kind: ConfigMap
metadata:
  name: autoresponder
  namespace: default
data:
  index.php: |
    <?php http_response_code(basename($_SERVER["REQUEST_URI"])); echo http_response_code();?>
  auto.php: |
    <?php for ($i=0;$i<1000;$i++) {
     $a=$_SERVER['HTTP_X_SCHEME']."://".$_SERVER['SERVER_NAME'].dirname($_SERVER["REQUEST_URI"])."/";
     echo "#".(1000-$i).": ".$a." ".@file_get_contents($a)."<br>"; flush();
     usleep(100000);
    }?>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: w3test1
  namespace: default
  labels:
    app: w3test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w3test1
  template:
    metadata:
      labels:
        app: w3test1
    spec:
      containers:
      - image: php:8-apache-buster
        name: php-1
        volumeMounts:
        - mountPath: /var/www/html/w3test1/100
          name: autoresponder
        - mountPath: /var/www/html/w3test1/200
          name: autoresponder
        - mountPath: /var/www/html/w3test1/300
          name: autoresponder
        - mountPath: /var/www/html/w3test1/400
          name: autoresponder
        - mountPath: /var/www/html/w3test1/500
          name: autoresponder
      volumes:
      - configMap:
          name: autoresponder
        name: autoresponder
---
apiVersion: v1
kind: Service
metadata:
  name: service-w3test1
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: w3test1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-w3test1
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: service-w3test1
          servicePort: 80
        path: /w3test1
