apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: w3test1-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: w3test1
  name: w3test1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w3test1
  template:
    metadata:
      labels:
        app: w3test1
    spec:
      containers:
      - image: php:8-apache-buster
        name: php-1
        volumeMounts:
        - mountPath: /var/www/html
          name: www
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: w3test1-data
---
apiVersion: v1
kind: Service
  name: svc-w3test1
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: w3test1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress-grafana
  namespace: default
spec:
  rules:
  - host: 35.224.24.249.xip.io
    http:
      paths:
      - backend:
          serviceName: svc-w3test1
          servicePort: 80
        path: /w3test1
